name: Build Push Artifact Deploy with Nexus

on:
  push:
    branches:
      - main

env:
  APP_NAME: fastapi-prod-cicd
  ARTIFACT_NAME: app.tar.gz
  NEXUS_REPO: python-artifacts

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build Python artifact
        run: |
          chmod +x scripts/build_artifact.sh
          ./scripts/build_artifact.sh

      - name: Upload artifact to Nexus
        run: |
          curl -u "${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }}" \
            --upload-file build/${{ env.ARTIFACT_NAME }} \
            "${{ secrets.NEXUS_URL }}/repository/${{ env.NEXUS_REPO }}/${{ env.APP_NAME }}/${{ github.sha }}/${{ env.ARTIFACT_NAME }}"

      - name: Deploy artifact on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-prod-cicd
            git pull origin main

            chmod +x scripts/deploy_from_nexus.sh

            ./scripts/deploy_from_nexus.sh \
              "${{ secrets.NEXUS_URL }}/repository/${{ env.NEXUS_REPO }}/${{ env.APP_NAME }}/${{ github.sha }}/${{ env.ARTIFACT_NAME }}" \
              "${{ secrets.NEXUS_USER }}" \
              "${{ secrets.NEXUS_PASSWORD }}"
